### ISSUE TITLE
Domtesting Component Issue

### ISSUE THREAD

**Issue by Tomek6789** [juristr/angular-testing-recipes#6]
Hello,

I have question about one test. 

If I change in this line: https://github.com/juristr/angular-testing-recipes/blob/master/src/app/components/domtesting.component.spec.ts#L12

ngIf="isVisible" to *ngIf="!isVisible"

Than karma throw ERROR: Disconnected, because no message in 10000 ms..

Do you know why this happens ?
I tested this also on PhantomJS browser and there this error also happens.

I think there is some issue in connection between browser and karma ? 

In my opnion tests should alwasys give passed or failed result on finish. This ERROR should never occure.

**Comment by Tomek6789** [comment]
I just found that if you updata jasmine-core to latest package it will fixed this bug.

**Comment by juristr** [comment]
Oh yes. I had this issue in one of my apps recently and as you said upgrading fixed the issue. I'll update this repo with new tests in the coming weeks, so I'll also upgrade Jasmine.

Thanks for letting me know 👍
