### ISSUE TITLE
not able to run the application

### ISSUE THREAD

**Issue by nizar-github** [juristr/angular-testing-recipes#7]
test is running fine.. but when running application using ng-serve getting below error

ERROR in src/app/utils/custom-matchers.ts(22,37): error TS2503: Cannot find namespace 'jasmine'.
src/app/utils/custom-matchers.ts(80,30): error TS2503: Cannot find namespace 'jasmine'.
src/app/utils/helpers.ts(71,10): error TS2304: Cannot find name 'expect'.
src/app/utils/helpers.ts(92,35): error TS2304: Cannot find name 'expect'.

**Comment by juristr** [comment]
Hey @nizar-github that can totally be. Actually I never tried to run the application as the main goal of this repository is not the application, but rather to showcase the testing scenario. For that I didn't take the approach of creating a somehow real-world app and then writing unit tests against it, but I rather create components & services with the only purpose of representing a certain test scenario which I then solve in a proper test case I add.

You can find the links in the README.md. I've also applied a couple of changes and added further tests (i.e. of routing etc.) which I haven't yet linked as I need to still test them a bit.

Anyway, thanks for your comment. Maybe I should add a note about this in the README, just to make it clear 😃

**Comment by nizar-github** [comment]
Thanks for the reply and your contribution for understanding unit test is
really helped me in a greater level. Great work and keep going!!


Regards,
Nizar
